service: lp-bot

package:
  exclude:
    - node_modules/aws-sdk/**/*

provider:
  name: aws
  runtime: nodejs12.x

functions:
  tracker:
    handler: src/index.tracker
    events:
      - http:
          path: tracker
          method: post
